# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c39a06b2bf64be2ccbecf416434a004ebdc6eab88b76e80812f2beae43259d131f6da7cb1568adda77fec42f844c7321682e5b486266d84d17c3718d9efc5e7

test:
  secret_key_base: a3fb13b4080a88aeb0388a4732bfbd5055c5ad0d59d1cdae108604973b1462fce1c6e1684fead6a8a0dc53434e69b99d0622c66022e2b835d7c021fcf3c9afca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
